import "@/app/globals.css";
import AppProvider from "@/components/providers/AppProvider";
import NProgress from "@/components/providers/NProgress";
import Navbar from "@/components/shared/header/mainHeader/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Pacific Rim Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={cn("antialiased", inter.className)}>
          <div>
            <Navbar />
          </div>
          {/* <AgeRestrictionGuard></AgeRestrictionGuard> */}

          {children}

          <div>
            {/* <NewsletterPage />
            <Footer /> */}
          </div>
          <NProgress />
          <Toaster />
        </body>
      </html>
    </AppProvider>
  );
}
